### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by logan12344** [OpenVidu/openvidu-android-app#1]
Hello! Can you help me with openvidu android app? I see a black screen instead of interlocutors. Checked from two of their phones. :( And i used official server.
![photo_2019-08-27_18-04-19](https://user-images.githubusercontent.com/22130703/63784189-f2a63680-c8f6-11e9-8189-01135cdf88f0.jpg)

**Comment by CSantosM** [comment]
Hello,

It is a known issue and we are working on it. 
The app is working fine using openvidu-server deployed locally. However the videos appear black using the openvidu-server deployed on AWS. 

We think the problem is the order of arrival, shipment or storage of ice candidates. 

We don't know when the app will be ready to use. A PR would be welcome.

**Comment by hurali97** [comment]
Any updates ? Just ran this on my two androids and connected peers video is blank.

**Comment by in13month** [comment]
> Hello,
> 
> It is a known issue and we are working on it.
> The app is working fine using openvidu-server deployed locally. However the videos appear black using the openvidu-server deployed on AWS.
> 
> We think the problem is the order of arrival, shipment or storage of ice candidates.
> 
> We don't know when the app will be ready to use. A PR would be welcome.

Hi how to run openvidu-server deployed locally?

**Comment by micaelgallego** [comment]
We are still working in a new OpenVidu Android demo app. It will be published soon...
